FROM python:3.12-slim

WORKDIR /app

# Prevent Python from writing .pyc files and buffering stdout/stderr
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install packages:
COPY requirements.txt .
# RUN  pip install --no-cache-dir -r requirements.txt
RUN  pip install  -r requirements.txt

COPY /src ./src
# to change .env later, with docker env:
COPY .env .
COPY app.py .

EXPOSE 8000

# Use uvicorn to serve the app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]


